### ISSUE TITLE
Adicionar a função usuario_escolhe_jogada do jogoNIM

### ISSUE THREAD

**Issue by oliveiraeverton** [EngSoft-UFMS/algoritmos_e_programacao_1#11]
A função usuario_escolhe_jogada que recebe os parâmetros e solicita que o jogador informe sua jogada e verifica se o valor é válido.

Essa função é essencial para a funcionalidade do jogo;

**Comment by LourdesOshiroIgarashi** [comment]
Descrição do exercício para facilitar a implementação: [https://github.com/EngSoft-UFMS/algortimos_e_programacao_1/blob/main/ExercicioAvaliativo/jogoNIM.pdf](url)

**Comment by LourdesOshiroIgarashi** [comment]
Podemos implementar a função usuario_escolhe_jogada da seguinte forma:

1. A função usuario_escolhe_jogada recebe parâmetros n e m e solicita ao usuário que informe sua jogada. 
2. Ela verifica se o valor informado é válido (entre 1 e m, e não pode ser maior que o número de peças restantes n). 
3. Caso a jogada seja inválida, a função solicita novamente ao usuário que informe uma jogada válida.

**Comment by oliveiraeverton** [comment]
A imlementação não está perfeita, só passou em 60% dos casos de testes;

**Comment by oliveiraeverton** [comment]
O resultado dos testes com seu programa foi:

***** [0.32 pontos]: Checando partida unica (n = 5, m = 3, jogadas = (1,)) - Falhou *****
AssertionError: Deveria comecar com o computador

***** [0.32 pontos]: Checando partida unica (n = 5, m = 3, jogadas = (2,)) - Falhou *****
AssertionError: Deveria comecar com o computador

***** [0.32 pontos]: Checando partida unica (n = 9, m = 2, jogadas = (1, 2, 2)) - Falhou *****
AssertionError: Deveria comecar com o oponente

***** [0.32 pontos]: Checando partida unica (n = 9, m = 2, jogadas = (1, 2, 1)) - Falhou *****
AssertionError: Deveria comecar com o oponente

***** [0.32 pontos]: Checando partida unica (n = 11, m = 3, jogadas = (2, 3)) - Falhou *****
AssertionError: Deveria comecar com o computador

***** [0.01 pontos]: Checando partida unica que o computador ganha na primeira jogada (n = 25, m = 25, jogadas = ()) - Falhou *****
AssertionError: Deveria comecar com o computador

***** [0.01 pontos]: Checando partida unica que o computador ganha na primeira jogada (n = 2, m = 2, jogadas = ()) - Falhou *****
AssertionError: Deveria comecar com o computador

***** [0.01 pontos]: Checando partida unica que o computador ganha na primeira jogada (n = 1, m = 1, jogadas = ()) - Falhou *****
AssertionError: Deveria comecar com o computador

***** [0.12 pontos]: Checando campeonato (partida 1: n = 5, m = 3, jogadas = [1]; partida 2: n = 5, m = 3, jogadas = [2]; partida 3: n = 9, m = 2, jogadas = [1, 2, 2]) - Falhou *****
AssertionError: Deveria comecar com o computador
