### ISSUE TITLE
Adicionar a função computador_escolhe_jogada do jogoNIM

### ISSUE THREAD

**Issue by oliveiraeverton** [EngSoft-UFMS/algoritmos_e_programacao_1#12]
A função computador escolhe jogada recebe como parâmetros os números n e m e devolve um inteiro correspondente a quantidade de peças que deverá ser retirado do jogo.

A função é essencial para a funcionalidade do jogo.

**Comment by LourdesOshiroIgarashi** [comment]
Descrição do exercício para facilitar a implementação: [https://github.com/EngSoft-UFMS/algortimos_e_programacao_1/blob/main/ExercicioAvaliativo/jogoNIM.pdf](url)

**Comment by LourdesOshiroIgarashi** [comment]
Podemos implementar a função computador_escolhe_jogada da seguinte forma:

1. A função computador_escolhe_jogada recebe dois parâmetros: n (o número de peças restantes) e m (o limite máximo de peças que podem ser retiradas em cada jogada). Essa função é responsável por determinar a jogada do computador. 
2. Ela utiliza a estratégia vencedora descrita no enunciado, escolhendo sempre um número de peças que deixe um múltiplo de m+1 para o jogador oponente. 
3. Caso não seja possível, o computador retira o número máximo de peças permitido (m).

**Comment by oliveiraeverton** [comment]
exercicioAvaliativo/jogoNIM.pdf

**Comment by LourdesOshiroIgarashi** [comment]
O link vai direto para a descrição do repositório

**Comment by oliveiraeverton** [comment]
A imlementação não está perfeita, só passou em 60% dos casos de testes;

**Comment by oliveiraeverton** [comment]
O resultado dos testes com seu programa foi:

***** [0.32 pontos]: Checando partida unica (n = 5, m = 3, jogadas = (1,)) - Falhou *****
AssertionError: Deveria comecar com o computador

***** [0.32 pontos]: Checando partida unica (n = 5, m = 3, jogadas = (2,)) - Falhou *****
AssertionError: Deveria comecar com o computador

***** [0.32 pontos]: Checando partida unica (n = 9, m = 2, jogadas = (1, 2, 2)) - Falhou *****
AssertionError: Deveria comecar com o oponente

***** [0.32 pontos]: Checando partida unica (n = 9, m = 2, jogadas = (1, 2, 1)) - Falhou *****
AssertionError: Deveria comecar com o oponente

***** [0.32 pontos]: Checando partida unica (n = 11, m = 3, jogadas = (2, 3)) - Falhou *****
AssertionError: Deveria comecar com o computador

***** [0.01 pontos]: Checando partida unica que o computador ganha na primeira jogada (n = 25, m = 25, jogadas = ()) - Falhou *****
AssertionError: Deveria comecar com o computador

***** [0.01 pontos]: Checando partida unica que o computador ganha na primeira jogada (n = 2, m = 2, jogadas = ()) - Falhou *****
AssertionError: Deveria comecar com o computador

***** [0.01 pontos]: Checando partida unica que o computador ganha na primeira jogada (n = 1, m = 1, jogadas = ()) - Falhou *****
AssertionError: Deveria comecar com o computador

***** [0.12 pontos]: Checando campeonato (partida 1: n = 5, m = 3, jogadas = [1]; partida 2: n = 5, m = 3, jogadas = [2]; partida 3: n = 9, m = 2, jogadas = [1, 2, 2]) - Falhou *****
AssertionError: Deveria comecar com o computador

**Comment by oliveiraeverton** [comment]
Quando for finalizar essa issue, por favor fechar a #3
