### ISSUE TITLE
Adicionar resolução de lista sobre vetores do professor Edson Caceres da turma P03

### ISSUE THREAD

**Issue by wagnerUFMS** [EngSoft-UFMS/algoritmos_e_programacao_1#28]
Para o andar do projeto é necessário também a implementação de listas contendo os exercícios da disciplina, atráves delas a resolução de exercícios mais complexos, como os do beecrowd se tornarão mais recorrentes. Solicito que @JerffersonJunior  e @rafaelTsu   resolvam a lista 10 abordando vetores do módulo 3.1.1.

**Comment by JerffersonJunior** [comment]
Podemos dividir a lista meio a meio para desenvolver mais rapidamente @rafaelTsu, o que acha? 
Inclusive, como não são grandes, podemos separá-los em um único arquivo.py

**Comment by rafaelTsu** [comment]
Sim, pode ser. Me passa as partes que vou fazer.
