### ISSUE TITLE
Adicionar implementação da atividade 1 do exercício avaliativo

### ISSUE THREAD

**Issue by JerffersonJunior** [EngSoft-UFMS/algoritmos_e_programacao_1#29]
Realizar as seguintes tasks da 1° parte do exercício.

- [x] Faça um arquivo Python que imprima as informações do vendedor.
- [x] Faça um arquivo Python que imprima as informações do comprador.
- [x] Faça um arquivo Python que imprima os itens comprados pelo comprador.

@oliveiraeverton se possível, implemente-as juntamente com a atividade 2, visto que as duas apresentam correlação.

**Comment by oliveiraeverton** [comment]
Ok. Vou fazer para cada exercício um arquivo py.
