### ISSUE TITLE
Adicionar implementação da atividade 2 do exercício avaliativo

### ISSUE THREAD

**Issue by JerffersonJunior** [EngSoft-UFMS/algoritmos_e_programacao_1#30]
Realizar a construção do menu da 2° parte do exercício avaliativo:

- Construir um programa em Python que contenha um menu com as seguintes opções:

a. Ler um arquivo xml;
b. Informações do vendedor;
c. Informações do comprador;
d. Itens comprados;
e. Valor total da compra;
f. Fechar programa.

@oliveiraeverton você pode mesclar a 1° parte com a segunda caso seja viável.

**Comment by wagnerUFMS** [comment]
Você pode adicionar uma nova função a esse programa, função `Retira_Produto( )`. Ela tem como funcionalidade, retirar algum item da escolha do comprador que ele não deseja mais comprar. Caso o comprador desejar retirar o produto após o valor total ser fornecido , o valor total deverá ser alterado baseado no preço do item escolhido.
