### ISSUE TITLE
Adicionar função de retorna_perguntas do trabalho "Jogo de Perguntas e Respostas"

### ISSUE THREAD

**Issue by wagnerUFMS** [EngSoft-UFMS/algoritmos_e_programacao_1#45]
A primeira função do trabalho contém as perguntas armazenadas e as retornam, para posteriormente serem utilizadas no "Jogo de Perguntas e Respostas". As perguntas podem ser relacionadas a assuntos de diversas áreas de conhecimento, incluindo geografia , artes , história, ciências , entretenimento, esportes. Sejam criativos nas perguntas que irão utilizar, disponibilizem 4 opções de respostas e insiram a resposta correta.

**Comment by oliveiraeverton** [comment]
Não tinha no código a parte de selecionar qual a área é a pergunta, não tem uma classificação se é Geografia, Arte, História, ...; precisa fazer uma regra de negócio para isso.

**Comment by LourdesOshiroIgarashi** [comment]
Podemos colocar como padrão gerar as matérias aleatoriamente, mas ter a opção da pessoa escolher qual matéria ela quer responder as perguntas
