### ISSUE TITLE
Adicionar função de fazer_perguntas do trabalho "Jogo de Perguntas e respostas"

### ISSUE THREAD

**Issue by wagnerUFMS** [EngSoft-UFMS/algoritmos_e_programacao_1#46]
Outra funcionalidade requerida no trabalho que realiza a enumeração sequencial de cada resposta , de maneira que o usuário  escolha a sua opção através do número. Utilizem a função (enumerate): ela retorna uma tupla de dois elementos a cada iteração: um número sequencial e um item da sequência correspondente para implementar essa funcionalidade.

**Comment by JerffersonJunior** [comment]
Seria interessante se essa função de fazer perguntas pudesse ser alterada para receber um arquivo inserido pelo usuário. Poderia tornar o trabalho mais dinâmico para que duas pessoas pudessem jogar uma com a outra sem alterar diretamente o código do trabalho, mas sim enviando esse arquivo contendo as perguntas de preferência.
